### ISSUE TITLE
User can't create *@example.com => @otherdomain.com alias

### ISSUE THREAD

**Issue by harobed** [modoboa/modoboa-admin#32]
User can't create ```*@example.com``` => ```@otherdomain.com``` alias.

Solution : 

* user define *@example.com => *@otherdomain.com in modoboa-admin user interface
* append ```TRIM(LEADING '*' FROM al.extmboxes)``` here : https://github.com/modoboa/modoboa-admin/blob/master/modoboa_admin/postfix_maps.py#L66

What do you think about this solution ?

**Comment by harobed** [comment]
What do you think about this proposition ?

**Comment by tonioo** [comment]
As modoboa already provides a way to create domain aliases (based on http://www.postfix.org/postconf.5.html#virtual_alias_domains), we need to know what's the best mechanism.

**Comment by tonioo** [comment]
This issue was moved to tonioo/modoboa#803
