### ISSUE TITLE
Simple Sender-Address Management for smtpd_sender_login_maps

### ISSUE THREAD

**Issue by kokel** [modoboa/modoboa-admin#39]
Hello,

thanks for implementing support for all the sender_login_maps.
One feature I am missing here. We have several shared mailboxes users have access to via IMAP acls.
These shared mailboxes from modoboa point of view are normal accounts. 

For example the user ```user01@example.com``` should be able to send mails with MAIL FROM address of the shared mailboxes e.g. ```shared01@example.com```. With the current implementation this is not possible.

Please add support for simple ```allowed from addresses``` which can be configured e.g. for normal account identities in the mail context.

It also would be great to have some kind of overview for the allowed sender addresses. e.g. a listing for all accounts/aliases etc. which account is allowed to send mails in account of.

Thanks in advance!

**Comment by tonioo** [comment]
This issue was moved to tonioo/modoboa#802
